// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbongxcpwfeoyxqdgyso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpib25neGNwd2Zlb3l4cWRneXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTM3NzgsImV4cCI6MjA2NzQ4OTc3OH0.PnJMBQbroNnw2spLIU7-u19xnkWk1X7yFFp8W3Ersq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});